example/django/Django_site/Django_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('tovar/', include('tovar.urls')),
    path('admin/', admin.site.urls),
]

example/django/Django_site/home/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.urls import path 

from .import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

example/django/Django_site/tovar/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.urls import path 

from .import views

app_name = 'tovar'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:id_tovar>/', views.show, name = 'show'),
    path('<int:id_tovar>/edit/', views.edit, name = 'edit'),
    path('<int:id_tovar>/delete/', views.delete, name = 'delete'),
    path('<int:id_tovar>/tags/', views.tags, name = 'tags'),
    path('<int:id_tovar>/<str:pk_tag>/drop', views.drop_tag, name = 'drop_tag'),
    path('create/', views.create, name = 'create'),
    path('groups/', views.group_index, name = 'allgroups'),
    
]

example/django/Django_site/home/models.py
from django.db import models

# Create your models here.

example/django/Django_site/tovar/models.py
from django.db import models


#TODO add valuses by default = 0 inside BaseData for quantity 
class Tovar(models.Model):
    title = models.CharField(max_length=255, unique= True)
    article = models.CharField(max_length=16, null= True, blank=True, unique= True)
    description = models.TextField(null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0, blank=True)
    group = models.ForeignKey('tovar.Group',on_delete= models.PROTECT, null=True)
    tags = models.ManyToManyField('tovar.tag')

    def __str__(self):
        if self.article is None:
            return '{1} (---) {0}'.format(self.title, self.pk)
        else:
            return '{2} ({0}) {1}'.format(self.article, self.title, self.pk)
        
class Group(models.Model):
    title = models.CharField(max_length=128, unique =True)
    code = models.CharField(max_length=16, unique=True)
    soon = models.NullBooleanField()
    
    @property
    def full_title(self):
        return '({0}) {1}'.format(self.code, self.title)
    
    
    def __str__(self):
        return self.full_title
    
    
class Tag(models.Model):
    title = models.CharField(max_length=32, primary_key=True)
    
    
    def __str__(self):
        return self.title 

example/django/Django_site/tovar/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import Tovar 


class TagListForm(forms.Form):
        tag_list = forms.CharField(label='New', required=False)


class TovarForm(forms.Form):
    
    title = forms.CharField(label="Name", max_length=256)
    atricle = forms.CharField(label="Artcile", max_length=16)
    quantity = forms.IntegerField(label="Quantity", min_value=0)
    description = forms.CharField(label="Description", widget=forms.Textarea, required=False)
    

class TovarModelForm(forms.ModelForm):
    
    class Meta:
            model = Tovar
            fields = ['title', 'article', 'quantity', 'description']
            
        

example/django/Django_site/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from datetime import datetime


def index_full(request):
    
    current_time = datetime.now()
    
    context = {
        'current_time' : current_time
    }
    template = loader.get_template('home/index.html')
    text = template.render(context, request)
    return HttpResponse(text)

def index(request):
    
    current_time = datetime.now()
    return render( request, 'generic.html', locals() )

example/django/Django_site/tovar/views/create.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse 

from ..forms import TovarModelForm
from ..models import Tovar

from restful import restful


@restful
def create(request):
    tovar = Tovar()
    form = TovarModelForm(instance=tovar)
    
    return render(request, 'tovar/tovar_edit.html', locals()) 


@create.method('POST')
def create(request):
    tovar = Tovar()
    form = TovarModelForm(request.POST, instance=tovar)
    
    if form.is_valid():
        tovar = form.save()
        return HttpResponseRedirect(reverse('tovar:show', args=[tovar.pk]))
    else:
        return render(request, 'tovar/tovar_edit.html', locals())

example/django/Django_site/tovar/views/delete.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from ..models import Tovar


def delete(request, id_tovar):
    tovar = get_object_or_404(Tovar, pk=id_tovar)
    tovar.delete()
    return HttpResponseRedirect(reverse('tovar:index'))
    

example/django/Django_site/tovar/views/drop_tag.py
#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from textwrap import dedent
from django.db import connection
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect

from ..models import Tovar, Tag 


def drop_tag(request, id_tovar, pk_tag):
    with connection.cursor() as cursor:
        cursor.execute(
            dedent('''\
                delete 
                    from tovar_tovar_tags 
                    where tovar_id= %s 
                        and tag_id=%s ; '''), 
            [id_tovar, pk_tag]
        )
        
    return HttpResponseRedirect(reverse('tovar:tags', args=[id_tovar]))

def drop_tag_for_lamers(request, id_tovar, pk_tag):
    tovar = get_object_or_404(Tovar, pk=id_tovar)
    tag = get_object_or_404(Tovar, pk=pk_tag)
    tovar.tags.remove(tag)
    tovar.save()
    return HttpResponseRedirect(reverse('tovar:tags', args=[id_tovar]))

example/django/Django_site/tovar/views/edit.py
import sys

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from restful import restful
from ..models import Tovar
from ..forms import TovarForm, TovarModelForm

@restful
def edit(request, id_tovar):
    
    python_path = sys.path
    tovar = get_object_or_404(Tovar, pk=id_tovar)
    form = TovarModelForm(instance=tovar)
    return render(request, 'tovar/tovar_edit.html', locals()) 

@edit.method('POST')
def edit(request, id_tovar):
    
    raw_data = dict()
    raw_data.update(request.POST)
    
    tovar = get_object_or_404(Tovar, pk=id_tovar)
    
    form = TovarModelForm(request.POST, instance=tovar)
    if form.is_valid():
        form.save()
        return render(request, 'tovar/tovar_show.html', locals()) 
    else:
        return render(request, 'tovar/tovar_edit.html', locals()) 

example/django/Django_site/tovar/views/group_index.py
from django.shortcuts import render

from ..models import Tovar, Group


def group_index(request):
    all_groups = Group.objects.all()
    return render(request, 'tovar/allgroups.html', locals())

example/django/Django_site/tovar/views/index.py
from django.shortcuts import render


from ..models import Tovar


def index(request):
    all_tovars = Tovar.objects.all()
    return render(request, 'tovar/index.html', locals())

example/django/Django_site/tovar/views/show.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from ..models import Tovar


def show(request, id_tovar):
    tovar = get_object_or_404(Tovar, pk=id_tovar)
    tags = ','.join((tag.title for tag in tovar.tags.all() ))
    return render(request, 'tovar/tovar_show.html', locals()) 

example/django/Django_site/tovar/views/tags.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404, render

from ..models import Tovar
from  ..forms import TagListForm
from restful import restful


@restful
def tags(request, id_tovar):
    tovar = get_object_or_404(Tovar, pk=id_tovar)
    form = TagListForm()
    return render(request, 'tovar/tags.html', locals())


@tags.method('POST')
def tags(request, id_tovar):
    form = TagListForm(request.POST)
    if form.is_valid():
        tag_list = form.cleaned_data['tag_list']
        tovar = get_object_or_404(Tovar, pk=id_tovar)
        for pk_tag in map(str.strip, tag_list.split(',')):
            tag = Tag.get(pk=1)
            tovar.tags.add(tag)
        tovar.save()
    

example/django/Django_site/Django_site/templates/generic.html
{% load static %}

<html>
    <head>
        <title>{% block title %} Our Workshop {% endblock %} </title>
        <link rel="stylesheet" type="text/css" href="{% static 'mystyle.css' %}" />
    </head>
    <body bgcolor="#FFDEAD">
    
        <!-- Main menu-->
        <table>
            <tr>
                <td><a href="{% url 'home:index' %}">Home</a></td>
                <td><a href="{% url 'tovar:index' %}">Goods</a></td>
                <td><a href="{% url 'tovar:allgroups' %}">Groups</a></td>
            </tr>
        </table>
        <!-- End of main menu-->
        
        
        <!-- Main title-->
        <H1> {% block header %}This is our Workshop {% endblock %}</H1>
        
        
        <div id="contents">
        <!-- contents-->
        {% block contents %}
        <p>Welcome !!!</p>
        {% endblock %}
        </div>
        
    </body>
</html>

example/django/Django_site/home/templates/home/index.html
<html>
    <head><title> Cool Workshop </title></head>
    <body>
        
        <table>
            <tr>
                <td>Begin</td>
                <td>Items</td>
            </tr>
        </table>
        
        <H1> This is our workshop</H1>
        
        <div id="contents">
        <!-- Contents -->
        <p> Moscow time:  {{current_time}} </p>
        
        <p> Welcome !!! </p>
        
        </div>

    </body>
</html>

example/django/Django_site/tovar/templates/tovar/allgroups.html
    {% extends 'generic.html' %}

    {% block title %} Groups of goods {% endblock %}
    {% block header %} Groups of goods {% endblock %}

    {% block contents %}
    <table border='1'>
        <tr>
            <th>Code</th>
            <th>Name_of_group</th>
            <th>Perishable</th>
        </tr>
        {% for g in all_groups %}
        <tr>
            <td>{{ g.code }}</td>   
            <td>{{ g.title   }}</td>   
            <td>{{ g.soon}}</td>  
        </tr>
        {% endfor %}
    </table>
    {% endblock %}     
   

example/django/Django_site/tovar/templates/tovar/index.html
    {% extends 'generic.html' %}

    {% block title %} List of goods {% endblock %}
    {% block header %} List of goods {% endblock %}

    {% block contents %}
    <table border='1'>
        <tr>
            <th>Article</th>
            <th>Name_of_goods</th>
            <th>Availability</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        {% for t in all_tovars %}
        <tr>
            <td>{{ t.article }}</td>   <!-- Article-->
            <td>{{ t.title   }}</td>   <!-- Name-->
            <td>{{ t.quantity}}</td>   <!-- Availability-->
            <td>
                {% for tag in t.tags.all|slice:':5' %}
                    {{tag.title}}
                {% endfor%}
            </td>
            <td><a href="{% url 'tovar:show' t.pk %}">Views</a></td>
            <td><a href="{% url 'tovar:edit' t.pk %}">Edit</a></td>
            <td><a href="{% url 'tovar:tags' t.pk %}">Tags</a></td>
            <td><a href="{% url 'tovar:delete' t.pk %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    
    <p><a href="{% url 'tovar:create' %}"> New good </a></p>
    {% endblock %}     
   

example/django/Django_site/tovar/templates/tovar/tags.html
{% extends 'generic.html' %}

{% load static %}    

{% block header %} Tags for {{ tovar.title }} {% endblock %}

{% block contents %}
<ul>
    {% for t in tovar.tags.all %}
    <li>{{t.title}} &mdash; 
        <a href="{% url 'tovar:drop_tag' tovar.pk t.pk %}">
            <img src="{% static 'tovar/delete.png' %}" />
        </a>
    </li>
    {% endfor %}
</ul>
    
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value= "Add" />
</form>
    
{% endblock %}

example/django/Django_site/tovar/templates/tovar/tovar_edit.html
    {% extends 'generic.html' %}

    {% block title %} Good -- {{ tovar.title }} {% endblock %}
    {% block header %} {{ tovar.title }} {% endblock %}

    {% block contents %}
    
    <p>Request by method => {{request.method}}</p>
    <p>Raw data => {{ raw_data }}</p>
    
    
    <form method ="POST" action="">{% csrf_token %}
        <table border="0">
            <tr><td>{{ form.non_field_errors }}</td></tr>
            <tr>
                <td>Name</td>
                <td>{{form.title}}</td>
                <td>{{form.title.errors}}</td>
            </tr>
            <tr>
                <td>Article</td>
                <td>{{form.article}}</td>
                <td>{{form.article.errors}}</td>
            </tr>
            <tr>
                <td>Quantity</td>
                <td>{{form.quantity}}</td>
                <td>{{form.quantity.errors}}</td>
            </tr>
            <tr>
                <td>Description</td>
                <td>{{form.description}}</td>
                <td>{{form.description.errors}}</td>
            </tr>
            
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" />
                    <input type="reset" />
                </td>
            </tr>
        </table>
        
        
        
    </form>
    {% endblock%}
   

example/django/Django_site/tovar/templates/tovar/tovar_edit_old.html
    {% extends 'generic.html' %}

    {% block title %} Good -- {{ tovar.title }} {% endblock %}
    {% block header %} {{ tovar.title }} {% endblock %}

    {% block contents %}
    <form method ="POST" action="">{% csrf_token %}
    
        <table border="1">
            <tr>
                <td><label for="title"> Name </label></td>
                <td><input id="title" type="text" name="title" /> </td>
            </tr>
            <tr>
                <td><label for="quantity"> Availably</label></td>
                <td><input id="quantity" type="text" name="quntity" /></td>
            </tr>
        </table>
        
        <input type="submit" />
        <input type="reset" />
        
    </form>
    {% endblock%}
   

example/django/Django_site/tovar/templates/tovar/tovar_show.html
    {% extends 'generic.html' %}

    {% block title %} Good -- {{ tovar.title }} {% endblock %}
    {% block header %} {{ tocar.title }} {% endblock %}

    {% block contents %}
    <table border='1'>
        <tr><td>Name_of_goods</td><td> {{tovar.title}} </td></tr>
        <tr><td>Article</td><td> {{tovar.article}} </td></tr>
        <tr><td>Availability</td><td> {{tovar.quantity}} </td></tr>
        <tr><td>Description</td><td> {{tovar.description}} </td></tr>
        <tr><td>Group</td><td> {{tovar.group.title}} </td></tr>
        <tr><td>Tag</td><td> {{tags}} </td></tr>
        
    </table>
    
    
    <p> Временно </p>
    <ul>
        {% for tag in tovar.tags.all %}
        <li>{{tag.title}}</li>
        {%endfor%}
    </ul>
    {% endblock %}     
   